
FROM node:20-slim AS build
WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --legacy-peer-deps


COPY . .

RUN npm run build
FROM node:20-slim AS runner
WORKDIR /app

ARG NEXT_PUBLIC_KEYCLOAK_ISSUER
ARG KEYCLOAK_CLIENT_ID
ARG KEYCLOAK_CLIENT_SECRET
ARG NEXTAUTH_SECRET
ARG NODE_EXTRA_CA_CERTS
ARG NEXTAUTH_URL
ARG BACKEND_URL

ENV NEXT_PUBLIC_KEYCLOAK_ISSUER=${NEXT_PUBLIC_KEYCLOAK_ISSUER}
ENV KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
ENV KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
ENV NODE_EXTRA_CA_CERTS=${NODE_EXTRA_CA_CERTS}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ENV BACKEND_URL=${BACKEND_URL}

COPY --from=build /app/.next/standalone ./


COPY --from=build /app/.next/static ./.next/static


COPY --from=build /app/public ./public

COPY --from=build /app/certs ./certs

EXPOSE 3000

CMD ["node", "server.js"]